name: Provision EC2 + Build & Deploy petstore-api

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPO: ${{ vars.ECR_REPO }}
  IMAGE_TAG: latest
  TEMPLATE_FILE: cloudformation/ec2.yaml
  DEPLOY_TAG_KEY: ${{ vars.DEPLOY_TAG_KEY }}
  DEPLOY_TAG_VALUE: ${{ vars.DEPLOY_TAG_VALUE }}

jobs:
  ###############################
  # 1. PROVISION EC2 FROM AMI   #
  ###############################
  provision-ec2-cfn:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      STACK_NAME: petstore-ec2-${{ github.actor }}-${{ github.run_number }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation stack
        run: |
          set -euo pipefail
          set -x

          echo "STACK_NAME=${STACK_NAME}"
          echo "AWS_REGION=${AWS_REGION}"
          echo "TEMPLATE_FILE=${TEMPLATE_FILE}"

          ls -l "${TEMPLATE_FILE}"
          grep -n '^Outputs:' "${TEMPLATE_FILE}" || (echo_
